

from PyQt5 import QtCore, QtGui, QtWidgets

import  mysql.connector
from PyQt5.QtGui import QStandardItemModel


class Ui_threeWindow(object):
    def closeMain(self, three_w, main_w):
        three_w.hide()
    def setupUi(self, threeWindow,MainWindow):
        threeWindow.setObjectName("threeWindow")
        threeWindow.resize(728, 579)
        threeWindow.setStyleSheet("background-color: #fff; \n"
"border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(threeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.product_list = QtWidgets.QTreeView(self.centralwidget)
        self.product_list.setGeometry(QtCore.QRect(20, 280, 691, 261))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.product_list.setFont(font)
        self.product_list.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.product_list.setObjectName("product_list")
        self.model = QStandardItemModel()
        self.model.setHorizontalHeaderLabels(['Name', 'Price', 'Size', 'Brand', 'Weight', 'Year', 'Category', 'Id'])
        self.product_list.header().setDefaultSectionSize(80)
        self.product_list.setModel(self.model)
        self.product_list.pressed.connect(self.getValue)
        self.price_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.price_edit.setGeometry(QtCore.QRect(110, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.price_edit.setFont(font)
        self.price_edit.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.price_edit.setObjectName("price_edit")
        self.name_lbl = QtWidgets.QLabel(self.centralwidget)
        self.name_lbl.setGeometry(QtCore.QRect(40, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.name_lbl.setFont(font)
        self.name_lbl.setStyleSheet(" color: #600080;")
        self.name_lbl.setObjectName("name_lbl")
        self.price_lbl = QtWidgets.QLabel(self.centralwidget)
        self.price_lbl.setGeometry(QtCore.QRect(40, 80, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.price_lbl.setFont(font)
        self.price_lbl.setStyleSheet(" color: #600080;")
        self.price_lbl.setObjectName("price_lbl")
        self.size_lbl = QtWidgets.QLabel(self.centralwidget)
        self.size_lbl.setGeometry(QtCore.QRect(40, 130, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.size_lbl.setFont(font)
        self.size_lbl.setStyleSheet(" color: #600080;")
        self.size_lbl.setObjectName("size_lbl")
        self.brand_lbl = QtWidgets.QLabel(self.centralwidget)
        self.brand_lbl.setGeometry(QtCore.QRect(40, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.brand_lbl.setFont(font)
        self.brand_lbl.setStyleSheet(" color: #600080;")
        self.brand_lbl.setObjectName("brand_lbl")
        self.weight_lbl = QtWidgets.QLabel(self.centralwidget)
        self.weight_lbl.setGeometry(QtCore.QRect(280, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.weight_lbl.setFont(font)
        self.weight_lbl.setStyleSheet(" color: #600080;")
        self.weight_lbl.setObjectName("weight_lbl")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(110, 31, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.name_edit.setFont(font)
        self.name_edit.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.name_edit.setObjectName("name_edit")
        self.year_lbl = QtWidgets.QLabel(self.centralwidget)
        self.year_lbl.setGeometry(QtCore.QRect(290, 80, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.year_lbl.setFont(font)
        self.year_lbl.setStyleSheet(" color: #600080;")
        self.year_lbl.setObjectName("year_lbl")
        self.category_lbl = QtWidgets.QLabel(self.centralwidget)
        self.category_lbl.setGeometry(QtCore.QRect(280, 180, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.category_lbl.setFont(font)
        self.category_lbl.setStyleSheet(" color: #600080;")
        self.category_lbl.setObjectName("category_lbl")
        self.size_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.size_edit.setGeometry(QtCore.QRect(110, 130, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.size_edit.setFont(font)
        self.size_edit.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.size_edit.setObjectName("size_edit")
        self.brand_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.brand_edit.setGeometry(QtCore.QRect(110, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.brand_edit.setFont(font)
        self.brand_edit.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.brand_edit.setObjectName("brand_edit")
        self.weight_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.weight_edit.setGeometry(QtCore.QRect(370, 130, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.weight_edit.setFont(font)
        self.weight_edit.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.weight_edit.setObjectName("weight_edit")
        self.category_combo = QtWidgets.QComboBox(self.centralwidget)
        self.category_combo.setGeometry(QtCore.QRect(370, 180, 131, 31))
        self.category_combo.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.category_combo.setObjectName("category_combo")
        self.category_combo.addItem('Computer')
        self.category_combo.addItem('Mobile')
        self.category_combo.addItem('Tablet')
        self.category_combo.addItem('Camera')
        self.year_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.year_edit.setGeometry(QtCore.QRect(370, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.year_edit.setFont(font)
        self.year_edit.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.year_edit.setObjectName("year_edit")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget,clicked = lambda :self. add_product())
        self.add_btn.setGeometry(QtCore.QRect(560, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("border-radius: 8px;\n"
"background-color:#600080 ;\n"
"color: #ffffff;")
        self.add_btn.setObjectName("add_btn")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget,clicked = lambda :self. delete_product())
        self.delete_btn.setGeometry(QtCore.QRect(560, 100, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("border-radius: 8px;\n"
"background-color:#600080 ;\n"
"color: #ffffff;")
        self.delete_btn.setObjectName("delete_btn")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget,clicked = lambda :self. update_product())
        self.update_btn.setGeometry(QtCore.QRect(560, 160, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.update_btn.setFont(font)
        self.update_btn.setStyleSheet("border-radius: 8px;\n"
"background-color:#600080 ;\n"
"color: #ffffff;")
        self.update_btn.setObjectName("update_btn")
        self.search_lbl = QtWidgets.QLabel(self.centralwidget)
        self.search_lbl.setGeometry(QtCore.QRect(30, 230, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.search_lbl.setFont(font)
        self.search_lbl.setStyleSheet(" color: #600080;")
        self.search_lbl.setObjectName("search_lbl")
        self.search_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_edit.setGeometry(QtCore.QRect(110, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.search_edit.setFont(font)
        self.search_edit.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.search_edit.setObjectName("search_edit")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget,clicked = lambda :self. search_product())
        self.search_btn.setGeometry(QtCore.QRect(240, 230, 41, 31))
        self.search_btn.setStyleSheet("border-radius: 8px;\n"
"background-color:#600080 ;\n"
"color: #ffffff;")
        self.search_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/search.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.search_btn.setIcon(icon)
        self.search_btn.setObjectName("search_btn")
        self.id_lbl = QtWidgets.QLabel(self.centralwidget)
        self.id_lbl.setGeometry(QtCore.QRect(290, 40, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.id_lbl.setFont(font)
        self.id_lbl.setStyleSheet(" color: #600080;")
        self.id_lbl.setObjectName("id_lbl")
        self.id_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.id_edit.setGeometry(QtCore.QRect(370, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.id_edit.setFont(font)
        self.id_edit.setStyleSheet("background-color: #DEDEDE; color: #010A1A;\n"
"border-radius: 8px;")
        self.id_edit.setObjectName("id_edit")
        threeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(threeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 26))
        self.menubar.setObjectName("menubar")
        threeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(threeWindow)
        self.statusbar.setObjectName("statusbar")
        threeWindow.setStatusBar(self.statusbar)
        self.user_lbl = QtWidgets.QLabel(self.centralwidget)
        self.user_lbl.setGeometry(QtCore.QRect(60, 0, 40, 38))
        self.user_lbl.setText("")
        self.user_lbl.setObjectName("user_lbl")
        self.logout_btn = QtWidgets.QPushButton(self.centralwidget,clicked = lambda :self.closeMain(threeWindow, MainWindow))
        self.logout_btn.setGeometry(QtCore.QRect(1, 0, 61, 21))
        self.logout_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/logout.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.logout_btn.setIcon(icon1)
        self.logout_btn.setIconSize(QtCore.QSize(24, 24))
        self.logout_btn.setObjectName("logout_btn")
        self.retranslateUi(threeWindow)
        QtCore.QMetaObject.connectSlotsByName(threeWindow)
        self.mydb = mysql.connector.connect(host='localhost',
                                            user='root',
                                            password='A2980305014',
                                            database='products_managements')
        self.my_cursor = self.mydb.cursor()
        # self.my_cursor.execute("CREATE DATABASE products_management")
        self.my_cursor.execute(
                "CREATE TABLE IF NOT EXISTS product(name varchar(255), price varchar(255), size varchar(255), brand  varchar(255), weight varchar(255), year varchar(255), category varchar(255), id INT(5))")
        self.products_list()
    def getValue(self):
        lst = []
        for idx in self.product_list.selectedIndexes():
            crawler = idx.model().itemData(idx)
            lst.append(crawler[0])
        self.id_edit.setText(str(lst[7]))
        self.name_edit.setText(lst[0])
        self.size_edit.setText(lst[1])
        self.price_edit.setText(lst[2])
        self.brand_edit.setText(lst[3])
        self.weight_edit.setText(lst[4])
        self.year_edit.setText(lst[5])
        # self.search_edit.setText(lst[6])
    def search_product(self):
        searched = self.search_edit.text()
        sql_command = "SELECT * FROM product WHERE id = %s"
        id = (searched,)
        self.my_cursor.execute(sql_command, id)
        results = self.my_cursor.fetchall()
        self.model.removeRows(0,self.model.rowCount())
        for record in results:
            self.model.insertRow(0)
            for j,data in enumerate(record):
                self.model.setData(self.model.index(0, j),data)
        self.clear_fields()
    def update_product(self):
        sql_command = """UPDATE product SET name=%s, price=%s, size=%s, brand=%s, weight=%s,  year=%s, category=%s  WHERE id=%s"""
        name = self.name_edit.text()
        price =self.price_edit.text()
        size = self.size_edit.text()
        brand = self.brand_edit.text()
        weight = self.weight_edit.text()
        year = self.year_edit.text()
        category = self.category_combo.currentText()
        id = self.id_edit.text()
        inputs = (name ,price, size, brand , weight, year, category,id)
        self.my_cursor.execute(sql_command, inputs)
        self.mydb.commit()
        self.model.removeRows(0, self.model.rowCount())
        #
        self.clear_fields()
        self.products_list()

    def add_product(self):
        print(self.name_edit.text())
        values = (self.name_edit.text(),self.price_edit.text(),self.size_edit.text(),self.brand_edit.text(),self.weight_edit.text(),self.year_edit.text(),self.category_combo.currentText(),self.id_edit.text())
        print(values)
        sql_command = "INSERT INTO product(name,price,size,brand,weight, year, category,id) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)"
        self.my_cursor.execute(sql_command,values)
        self.mydb.commit()
        self.model.removeRows(0, self.model.rowCount())
        self.products_list()
        self.clear_fields()

    def clear_fields(self):
        self.name_edit.clear()
        self.price_edit.clear()
        self.size_edit.clear()
        self.brand_edit.clear()
        self.weight_edit.clear()
        self.year_edit.clear()
        self.id_edit.clear()
        self.search_edit.clear()
    def products_list(self):
        self.my_cursor.execute("SELECT * FROM product")
        records = self.my_cursor.fetchall()
        for record in records:
            self.model.insertRow(0)
            for j,data in enumerate(record):
                self.model.setData(self.model.index(0, j),data)

    def delete_product(self):
        items = self.product_list.selectedIndexes()
        self.model.removeRow(items[0].row(), items[0].parent())
        sql_command = "DELETE from product WHERE id=%s"
        input = self.id_edit.text()
        self.my_cursor.execute(sql_command, (input,))
        self.mydb.commit()
        self.clear_fields()
    def retranslateUi(self, threeWindow):
        _translate = QtCore.QCoreApplication.translate
        threeWindow.setWindowTitle(_translate("threeWindow", "Products"))
        self.name_lbl.setText(_translate("threeWindow", "Name"))
        self.price_lbl.setText(_translate("threeWindow", "Price"))
        self.size_lbl.setText(_translate("threeWindow", "Size"))
        self.brand_lbl.setText(_translate("threeWindow", "Brand"))
        self.weight_lbl.setText(_translate("threeWindow", "Weight"))
        self.year_lbl.setText(_translate("threeWindow", "Year"))
        self.category_lbl.setText(_translate("threeWindow", "Category"))
        self.year_edit.setPlaceholderText(_translate("threeWindow", "../../...."))
        self.add_btn.setText(_translate("threeWindow", "Add"))
        self.delete_btn.setText(_translate("v", "Delete"))
        self.update_btn.setText(_translate("threeWindow", "Update"))
        self.search_lbl.setText(_translate("threeWindow", "Search"))
        self.id_lbl.setText(_translate("threeWindow", "ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    threeWindow = QtWidgets.QMainWindow()
    ui = Ui_threeWindow()
    ui.setupUi(threeWindow)
    threeWindow.show()
    sys.exit(app.exec_())
